### ISSUE TITLE
[bug] Sample plotting before and after missing plots

### ISSUE THREAD

**Issue by arose20** [Issacgoh/scENTInEL#2]
Hi,

When using the `scentinel.empirical_bayes_balanced_stratified_KNN_sampling` function if you pass in too many labels in `feat_use` this causes an issue with the before and after sampling plots.

Maybe if pass over a certain number of unique categories change plot to a histogram rather than plotting each label?

<img width="769" alt="Screenshot 2023-07-28 at 17 05 18" src="https://github.com/Issacgoh/scENTInEL/assets/60136364/664a960c-4f59-401e-97c8-3ddd7a04754b">

**Comment by Issacgoh** [comment]
Hi, the bug has been fixed in patch for branch prototype_v0.1.0 and merged into main (0541843..473e747). 
New update now differentiates plots for >120 classes and switches to a binned histogram instead. Classes/bins still retain ordering such that direct side-by-side comparisons can still be done.

![Screenshot 2023-07-28 at 19 25 33](https://github.com/Issacgoh/scENTInEL/assets/46449131/d9f7dc76-36e9-4508-b437-98825d06d0d2)
